name: Ping Google about updated sitemap

on:
  workflow_dispatch:

jobs:
  ping:
    name: Ping Google
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP GET request
        run: curl http://www.google.com/ping?sitemap=https://devdesignfun.com/sitemap.xml